previewsEnabled: true
services:
- type: web
  name: vote
  healthCheckPath: /
  runtime: docker
  plan: standard
  rootDir: vote
  autoDeploy: true
  envVars:
  - key: OPTION_A
    value: "LK-99 is real"
  - key: OPTION_B
    value: "LK-99 is fake"
  - key: REDIS_URL
    fromService:
      type: redis
      name: vote-redis
      property: connectionString
- type: web
  name: result
  rootDir: result
  healthCheckPath: /
  runtime: docker
  plan: standard
  autoDeploy: true
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: vote-db
      property: connectionString
- type: worker
  runtime: docker
  name: worker
  rootDir: worker
  plan: standard
  autoDeploy: true
  envVars:
  - key: PG_HOST
    fromDatabase:
      name: vote-db
      property: host
  - key: PG_USER
    fromDatabase:
      name: vote-db
      property: user
  - key: PG_PASSWORD
    fromDatabase:
      name: vote-db
      property: password
  - key: REDIS_HOST
    fromService:
      type: redis
      name: vote-redis
      property: host
- type: redis
  name: vote-redis
  ipAllowList: [] # no public IPs
databases:
- name: vote-db
  ipAllowList: [] # no public IPs
